### ISSUE TITLE
Merge `svelte:compiler` and `svelte:core`

### ISSUE THREAD

**Issue by klaussner** [meteor-svelte/meteor-svelte#16]
I think we don't need two separate packages anymore since the file extension can be configured with `package.json` instead of `svelte:compiler-html`. Having only one package would make updating a little more convenient. Any objections, @zimme? :slightly_smiling_face:

**Comment by zimme** [comment]
Go for it, unless. You can think of another reason for keeping them separate

**Comment by klaussner** [comment]
Merged it in https://github.com/meteor-svelte/meteor-svelte/commit/a7ffb4b3fd6f48b8d9a5c209e05c53f19cb9ee67. :slightly_smiling_face:
