### ISSUE TITLE
Meteor 1.8 Uncaught Error: 'target' is a required option

### ISSUE THREAD

**Issue by mahadoang** [meteor-svelte/meteor-svelte#18]
Meteor 1.8 
**Error** Uncaught Error: 'target' is a required option

**options.name should be capitalised**

How to fixed

Thank you

**Comment by klaussner** [comment]
Can you share a reproduction repository that demonstrates the error?

**Comment by mahadoang** [comment]
This is repository

https://github.com/mahadoang/meteor-svelte.git

Thank you

**Comment by klaussner** [comment]
I published a new version of the compiler (`2.13.5_2`). Can you try it again after running `meteor update svelte:compiler`?
