### ISSUE TITLE
[Question] Complete integration

### ISSUE THREAD

**Issue by alexandesigner** [meteor-svelte/meteor-svelte#22]
Is it possible to have an integration between (Tracker + SSR and possibly Apollo) all in one place?

I tried but no working, It might be interesting to have another example with all the resources

**Comment by klaussner** [comment]
> I tried but no working

Could you be a little more specific or provide a link to a reproduction that demonstrates what doesn't work? :slightly_smiling_face:

**Comment by alexandesigner** [comment]
First of all, this is awesome integration, [SSR + Tracker](https://github.com/alexandesigner/svelte-ssr-tracker).

I was able to run the SSR example along with the Tracker bringing the mongo data, before I was having a problem and this error was coming up for me:

``Error: Can not call yield in a noYieldsAllowed block!``

However, I was able to run and now the only problem might be the rendering of the dynamic component. Look at the image below, see divs (message and person):

![Screen Shot 2019-06-11 at 3 14 52 PM](https://user-images.githubusercontent.com/3044907/59296338-1ba21e00-8c5c-11e9-93fa-4bd182de1368.png)

In case I'm using SSR, the html was to render, right? 

Please let me know if I am doing something wrong or if you have a better practice.

**Comment by klaussner** [comment]
I've opened a PR on your repo: https://github.com/alexandesigner/svelte-ssr-tracker/pull/1. You basically need to do two additional things:

1. Load the data on the server (in the `onPageLoad` function) and pass it to the component's `render` function.
2. Serialize the data to JSON on the server, append it to the HTML, and use it on the client to initialize the hydrated component.

I hope this helps. 🙂

**Comment by alexandesigner** [comment]
Perfect, it was just that :smile:  

Thank you so much!
