### ISSUE TITLE
Using apollo with meteor-svelte

### ISSUE THREAD

**Issue by zimme** [meteor-svelte/meteor-svelte#3]
Let's use this issue to talk about what's needed to use Apollo properly with Svelte in a Meteor app.

Do we need to create a package to enable tighter integration, I don't think we need to do this.

It might be needed for graphql subscriptions, if the result is represented as a Tracker based result set, but maybe rxjs or some other observable implementation could be used instead?

Anyways, let's keep the discussion going and see what comes of it.

**Comment by klaussner** [comment]
I've created an example that shows how Meteor, Svelte, and Apollo can be used together: https://github.com/meteor-svelte/apollo-example. It uses the Apollo Client API, which is pretty straightforward. There's also the [`svelte-apollo`](https://github.com/timhall/svelte-apollo) package, a small wrapper for the API.

I don't think there's much to do in terms of GraphQL subscriptions. They need a separate WebSocket with a separate protocol and the `subscriptions-transport-ws` package should work without a Meteor-specific integration package.

**Comment by zimme** [comment]
Awesome work! 🎉 🍹
