### ISSUE TITLE
Error updating Svelte > 3.6.10 with 4.0.0-beta.0

### ISSUE THREAD

**Issue by CaptainN** [meteor-svelte/meteor-svelte#32]
Trying out Meteor Svelte 4.0.0-beta.0, I keep hitting this error with any version newer than 3.6.10 (including 3.6.11):

```
Uncaught (in promise) TypeError: store.subscribe is not a function
    at subscribe (index.mjs:41)
    at instance (Router.svelte:14)
    at init (index.mjs:1228)
    at new Router (Router.svelte:105)
    at Array.create_default_slot (App.svelte:33)
    at create_slot (index.mjs:55)
    at create_fragment (npdev_svelte-loadable.js?hash=b06f54066c982012946fa3443696c1575cf85b8a:129)
    at init (index.mjs:1240)
    at new svelte_loadable_provider_client (npdev_svelte-loadable.js?hash=b06f54066c982012946fa3443696c1575cf85b8a:183)
    at create_fragment (App.svelte:25)
```

You can see it by updating to any version of svelte newer than 3.6.10 in my [meteor svelte starter](https://github.com/CaptainN/meteor-svelte-starter). I don't actually know if this is a meteor-svelte incompatibility or something in `svelte-routing` or `svelte-loadable`.

**Comment by klaussner** [comment]
It looks like the signature of an internal Svelte function changed from `subscribe(component, store, callback)` in 3.6.10 to `subscribe(store, callback)` in 3.6.11. If a Svelte component that was compiled with 3.6.10 or older is used with components compiled with 3.6.11, this function receives a component instance instead of a store as its first argument.

Maybe you can fix this by updating `svelte:compiler` here: https://github.com/CaptainN/npdev-svelte-loadable/blob/e2cffecec3c2d454a30c052cb0f1de5c88842b09/package.js#L10.

**Comment by CaptainN** [comment]
I'm actually overriding that version in packages using the ! method. So it's already loading 4.x. I'll look at the modules of svelte-routing and svelte-loadable and see if something is precompiled.

**Comment by CaptainN** [comment]
I think svelte-routing is distributed as source (this seems common for svelte packages on npm?). I'm also using a local copy of npdev-svelte-loadable, so that's being compiled by Meteor with Meteor Svelte 4.0, afaict. I guess I'll just stick with 3.6.10 for now.

**Comment by CaptainN** [comment]
I've removed Svelte-routing and svelte-loadable - it still does this. Can this be caused by the client/server compilers getting crossed somehow?

**Comment by CaptainN** [comment]
I figured out that this is because Meteor is using the precompiled version of svelte-routing or svero (I tried switching it). I'll triple check all the compiler settings to make sure it's not something in my config.

**Comment by CaptainN** [comment]
Gah, it was just a configuration problem - something wasn't working in the meteor->nodeModules->recompile setting. Switching it to use a boolean instead of an array of platforms seems to have fixed it.

```json
{
  "meteor": {
    "mainModule": {
      "client": "client/main.js",
      "server": "server/main.js"
    },
    "testModule": "tests/main.js",
    "nodeModules": {
      "recompile": {
        "svelte-routing": true,
        "svelte-loadable": true
      }
    }
}
```

I'll follow-up with Meteor if I see the problem again.

**Comment by klaussner** [comment]
Glad to hear that it's working now. I'll include a section about the recompile settings in the README.md of the next version.
