### ISSUE TITLE
Problems importing Svelte components from package

### ISSUE THREAD

**Issue by arggh** [meteor-svelte/meteor-svelte#33]
Importing Svelte components from a package that has `svelte` as a dependency will break a Meteor app that uses `svelte:compiler`.

**Scenario:**

_my-svelte-components/package.json_
```json
{
   "name": "@arggh/my-svelte-components",
   "svelte": "index.js",
   "dependencies": {
      "svelte": "3.7.1"
   }
}
```

_app/package.json_
```json
{
   "name": "my-meteor-app",
   "dependencies": {
      "@arggh/my-svelte-components": "1.0.0",
      "svelte": "3.7.1"
   }
}
```

If the `svelte` dependency is removed from the package → Meteor app runs fine.

My guess is, this is somewhat related to these issues:

https://github.com/sveltejs/svelte/issues/3671
https://github.com/sveltejs/svelte/issues/3165
https://github.com/sveltejs/svelte/issues/3448

From what I quickly gathered, the problem is that there are multiple Svelte internal runtimes present in the app and they should deduplicated.

I tried this with the latest `4.0.0-beta` release as well.

**Comment by arggh** [comment]
The solution in my case appears to have been:

1. Add `svelte` in `pkg.devDependencies` or `pkg.peerDependencies`
2. Fix Storybook's webpack config (Storybook was the reason in put `svelte` in `pkg.dependencies`)

I'll re-open if I somehow manage to get multiple runtimes bundled again...

**Comment by stolinski** [comment]
I'm seeing this while using https://github.com/AlexxNB/tinro

https://github.com/stolinski/bboytools-2040 is a reproduction.

**Comment by arggh** [comment]
@stolinski the repro seems to be working fine for me, which is why I think you're encountering the caching issue related to `svelte:compiler` not considering the used Svelte version when using the compiler cache. Perhaps you updated the Svelte version at some point?

You should install the latest `svelte:compiler@4.0.0-beta.1` and do a `meteor reset` to get rid of the stale cache corrupting your bundle.

**Comment by arggh** [comment]
I also switched the import to reference a package instead of the entry point and all works:

![Screenshot 2020-05-20 at 9 20 19](https://user-images.githubusercontent.com/17210302/82411843-38092600-9a7b-11ea-875c-fdf2c1e8440f.png)

**Comment by arggh** [comment]
Also, I just noticed you have a version mismatch regarding `svelte:compiler` and the installed version of `svelte`.

Better to use `svelte:compiler@4.0.0-beta.1` so that the compiler always uses the same version as your app.

The path of a Meteor/Svelte-developer is currently rigged with several booby traps...

As a sidenote, I don't think Meteor leverages the `pkg.svelte` field in any meaningful way, but if you include a symlink to the package in `/imports` that might give you some of the same benefits.
