### ISSUE TITLE
load method from npm module can't export

### ISSUE THREAD

**Issue by CaptainN** [meteor-svelte/meteor-svelte#34]
I'm getting [an error using `svelte-loadable`](https://github.com/kaisermann/svelte-loadable/pull/19) where its `load` method is not exported from the package (`Loadable.svelte`). If I rename it, I can get it to export. I don't know if the error is in [Meteor core](https://github.com/meteor/meteor/issues/10790) or in `meteor-svelte`.

**Comment by CaptainN** [comment]
This appears to be an upstream [bug in svelte](https://github.com/sveltejs/svelte/issues/3983https://github.com/sveltejs/svelte/issues/3983)

**Comment by klaussner** [comment]
`svelte-loadable` should work with the latest version (3.16.4).
