### ISSUE TITLE
Error in web.browser.legacy build

### ISSUE THREAD

**Issue by gbuerk** [meteor-svelte/meteor-svelte#40]
Starting with a fresh project:
<pre>
meteor create --bare legacy-test-project
cd legacy-test-project
meteor add svelte:compiler
meteor npm i -s svelte@3.21.0
</pre>
I create a simple App.svelte and mount it to the body using:
<pre>
Meteor.startup(() => {
    new App({
        target: document.querySelector('body')
    })
})
</pre>

If I hit it using a "modern" user agent, everything works fine.  For example
<pre>
Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1
</pre>

However, if I hit it using a "legacy" user agent, it fails:
<pre>
Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_1 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.0 Mobile/14E304 Safari/602.1
</pre>

The error message from the console is:
<pre>
app.js?hash=4c618e8c0472a0480045bccc839d68edaa64428a:113 Uncaught TypeError: Class constructor SvelteComponentDev cannot be invoked without 'new'
    at new App (app.js?hash=4c618e8c0472a0480045bccc839d68edaa64428a:113)
    at main.js:4
    at maybeReady (meteor.js?hash=857dafb4b9dff17e29ed8498a22ea5b1a3d6b41d:938)
    at HTMLDocument.loadingCompleted (meteor.js?hash=857dafb4b9dff17e29ed8498a22ea5b1a3d6b41d:950)
</pre>

What's happening is that the older user agent is detected and the flow is routed to the web.browser.legacy build bundle.  

I'm not exactly sure why, but it appears that the compilation target of the legacy bundle is not compatible with the output of the svelte compiler.  Reading up on this, I am led to believe it may have something to do with the babel presets of the legacy bundle, which apparently target ES5.  I have attempted to overwrite the presets with a custom .babelrc, but have had no luck.

**Comment by HassanYA** [comment]
any update for this? I am facing the same issue trying to build an android app.
`Uncaught TypeError: Class constructor SvelteComponentDev cannot be invoked without 'new'`

**Comment by klaussner** [comment]
Can you try the suggestion in [this pull request](https://github.com/meteor-svelte/meteor-svelte/pull/43/files)?

**Comment by gbuerk** [comment]
That solved it for me.  Thank you!
