### ISSUE TITLE
Question: Optional Chaining on Svelte components

### ISSUE THREAD

**Issue by jaybeemind** [meteor-svelte/meteor-svelte#44]
Hi, has anyone managed to make "Optional chaining" work on svelte components?
Meteor already supports this in Blaze/Server.

[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining](url)

**Comment by daolutions** [comment]
@jaybeemind If you use the beta of svelte:compiler with
`meteor add svelte:compiler@4.0.0-beta.1`
you can use newer svelte versions. Since svelte 3.24.0 optional chaining is supported
