### ISSUE TITLE
Split up repository

### ISSUE THREAD

**Issue by klaussner** [meteor-svelte/meteor-svelte#5]
This repository contains three Atmosphere packages: `svelte:core`, `svelte:compiler`, and `svelte:compiler-no-html`. In the future, it could be split up to allow `svelte:core` to be used elsewhere. Currently, having everything in one repository should be fine because all packages are coupled together anyway.

**Comment by zimme** [comment]
Do we see a need for this yet? If so I could try and do it this weekend.

**Comment by klaussner** [comment]
I actually prefer the single repo because it makes updating the `svelte` dependency more convenient. 😄  Updates of `svelte:core` always result in version bumps for `svelte:compiler` and `svelte:compiler-no-html`, so I think it makes sense to keep them together.

**Comment by zimme** [comment]
Maybe we should look into [Lerna](/lerna/lerna)

**Comment by zimme** [comment]
Lerna might be unnecessary but I do think we should move the files related to `core` into it's own core folder just to make the separation a bit more clear.

**Comment by klaussner** [comment]
Separate `core` directory sounds good. :ok_hand:
