### ISSUE TITLE
Incompatible with Svelte 4?

### ISSUE THREAD

**Issue by davidsavoie1** [meteor-svelte/meteor-svelte#53]
I tried to launch a brand new Meteor project, installing `zodern:melte` then Svelte. However, when I tried to run the application, it crashed with error:

```
Error: Cannot find the `svelte` package in your application. Please install it with `meteor npm install `svelte`.
```
Svelte version had been set to the latest `4.1.1`. It seems that the library is incompatible with Svelte 4. I had to manually declare Svelte at version `3.59.2` for the application to start.

Thanks!

**Comment by TylerThompson** [comment]
I am also having this same issue

**Comment by davidsavoie1** [comment]
Any update on this issue? I'd like to be able to keep up to date with Svelte for other packages compatibility, but this constraint prevents me from doing so. Otherwise, what would be our options?

**Comment by zodern** [comment]
Svelte 4 requires Node 16 or newer. Until Meteor 3, Meteor is stuck on Node 14.

**Comment by zodern** [comment]
If anyone wants to, you could check if the svelte compiler seems to work in Node 14. Even if they dropped support, it's possible it would still work for now. If it does, we could add support for it.

**Comment by davidsavoie1** [comment]
Oh! I see! Sorry, I didn't realize that... Well, since I'm using it in Meteor, I'll probably stick to Svelte 3 for now anyway...
