### ISSUE TITLE
Configuration for file extensions

### ISSUE THREAD

**Issue by zimme** [meteor-svelte/meteor-svelte#8]
Can we use config options in `package.json`/`.svelterc` or some other way to eliminate the need for a separate `svelte:compiler-no-html` package?

**Comment by klaussner** [comment]
I generally prefer the "zero configuration" style for anything Meteor related but I agree that an option in `package.json` (under a `svelte:compiler` key?) would be better than a separate package in this case. 😄  I will open a PR for it next weekend.

**Comment by zimme** [comment]
Yeah, I'm unsure of where the best place is to have this option. I don't think `Meteor.settings` is available for build plugins. Which would be a good option. Maybe an environment variable? `package.json`?, `.svelterc`?
